dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

install:
  - npm install
  - npm install @sheetbase/core-server

before_script:
  - npm run transpile-test

script:
  - npm run lint
  - npm run test

after_success: npm run coverage